import { ClientIntlProvider } from "@/i18n/ClientIntlProvider";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import { theme } from "../../styles/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "aaa next-starter",
    description: "Generated by create next app",
};

type Props = {
    params: { lang: string };
    children: React.ReactNode;
};

export default function RootLayout({ params, children }: Props) {
    return (
        <html lang={params.lang}>
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <ClientIntlProvider>
                        <ThemeProvider theme={theme}>{children}</ThemeProvider>
                    </ClientIntlProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
