import { ClientIntlProvider } from "@/i18n/ClientIntlProvider";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { openSans } from "@/styles/fonts";
import "../../styles/globals.css";
import { theme } from "../../styles/theme";

export const metadata: Metadata = {
    title: "aaa next-starter",
    description: "Generated by create next app",
};

type Props = {
    params: { lang: string };
    children: React.ReactNode;
};

export default function RootLayout({ params, children }: Props) {
    return (
        <html lang={params.lang} className={openSans.className}>
            <body>
                <AppRouterCacheProvider>
                    <ClientIntlProvider>
                        <ThemeProvider theme={theme}>{children}</ThemeProvider>
                    </ClientIntlProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
